### PR TITLE
add kotlin arabic resources

### PR DESCRIPTION
**Pull request by MostafaMohamed2002**

### CODE REVIEW

**Comment by MostafaMohamed2002** [comment]
image

**Comment by ahmed-shehataa** [comment]
Hi mostafa, 
thank you for helping us
from your experience is that Kotlin resources are useful and How you rate them out of 10?

**Comment by MostafaMohamed2002** [comment]
I think its best kotlin  course in arabic
my rating is 8/10 because it doesn't have anything for data class and scoop functions

**Comment by ahmed-shehataa** [comment]
Great,
I'll merge it

**Pull request merged**
